# Generated by Django 4.1.7 on 2023-03-12 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_administrador',
        ),
    ]
