# Generated by Django 4.1.7 on 2023-03-12 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_usuario_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_activo',
        ),
    ]
