# Generated by Django 4.1.7 on 2023-05-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='tamanio',
            field=models.CharField(blank=True, max_length=2, verbose_name='tamanio'),
        ),
    ]
