# Generated by Django 4.1.7 on 2023-04-27 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asesorexterno',
            name='id_empresa',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='id_asesor_ext',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datos.asesorexterno', verbose_name='Asesor Externo'),
        ),
    ]
