# Generated by Django 4.1.7 on 2023-05-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0002_alter_empresa_tamanio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatusresidencia',
            name='comentarios_status',
            field=models.CharField(blank=True, max_length=1000, verbose_name='comentarios_status'),
        ),
    ]
