# Generated by Django 4.1.7 on 2023-04-27 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0002_remove_asesorexterno_id_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatusresidencia',
            name='id_practica',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datos.proyecto', verbose_name='Proyecto'),
        ),
    ]
