# Generated by Django 4.1.7 on 2023-05-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0003_alter_estatusresidencia_comentarios_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='correo',
            field=models.CharField(blank=True, max_length=200, verbose_name='correo'),
        ),
    ]
