# Generated by Django 4.1.7 on 2023-05-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0005_alter_proyecto_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_solicitud',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminacion'),
        ),
    ]
