# Generated by Django 4.1.7 on 2023-05-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0006_alter_proyecto_fecha_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
