# Generated by Django 4.1.7 on 2023-05-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0007_alter_alumno_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='correo'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='correo_institucional',
            field=models.EmailField(blank=True, max_length=254, verbose_name='correo_institucional'),
        ),
    ]
