# Generated by Django 4.1.7 on 2023-05-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0008_alter_alumno_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='correo',
            field=models.CharField(blank=True, max_length=254, verbose_name='correo'),
        ),
    ]
