# Generated by Django 4.1.7 on 2023-05-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0009_alter_alumno_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='pregunta',
            field=models.CharField(max_length=500, verbose_name='pregunta'),
        ),
    ]
