# Generated by Django 4.1.7 on 2023-05-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0010_alter_encuesta_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='pregunta',
            field=models.CharField(max_length=1000, verbose_name='pregunta'),
        ),
    ]
