# Generated by Django 4.1.7 on 2023-05-30 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0012_encuesta_id_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=1000, verbose_name='pregunta')),
                ('comentario', models.IntegerField()),
                ('id_alumno', models.CharField(blank=True, max_length=50, null=True, verbose_name='alumno')),
                ('id_asesor_ext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='datos.asesorexterno')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
