# Generated by Django 4.1.7 on 2023-05-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0013_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.CharField(max_length=1000, verbose_name='comentario'),
        ),
    ]
