# Generated by Django 4.1.7 on 2023-04-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField(verbose_name='id_usuario')),
                ('username', models.CharField(max_length=100, verbose_name='Nombre de usuario')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de usuario')),
                ('rol', models.IntegerField(verbose_name='id_usuario')),
                ('usuario_elim', models.CharField(max_length=100, verbose_name='Nombre de usuario')),
                ('deleted_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de eliminacion')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
            },
        ),
    ]
