# Generated by Django 4.1.7 on 2023-04-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='password',
            field=models.CharField(default='', max_length=100, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='usuario_elim',
            field=models.CharField(max_length=100, verbose_name='Nombre de usuario que elimina'),
        ),
    ]
